jobs:
  client:
    name: Client CI
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js for App
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install normal dependencies for App
        run: |
          yarn install --frozen-lockfile  # Opsiyonel bağımlılıkları dahil etmeden normal bağımlılıkları kuruyoruz.

      - name: Conditionally install optional dependencies (e.g., Docker specific)
        if: runner.os == 'Linux'  
        run: |
          yarn add @rollup/rollup-linux-x64-gnu --optional  # Opsiyonel bağımlılığı manuel olarak kuruyoruz.

      - name: Run build for App
        run: |
          yarn run build

      - name: Run TypeScript checks for App
        run: |
          yarn tsc --noEmit --skipLibCheck --strict # TypeScript kontrolleri çalıştırıyoruz.
