name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  client:
    name: Client CI
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Güncel sürüme geçildi.

      - name: Set up Node.js for App
        uses: actions/setup-node@v3  # Güncel sürüme geçildi.
        with:
          node-version: '20.x'

      - name: Install dependencies for App
        run: |
          yarn install --ignore-optional  # Opsiyonel bağımlılıkları göz ardı ederek kurulumu yapıyoruz.

      - name: Run build for App
        run: |
          yarn run build

      - name: Run TypeScript checks for App
        run: |
          yarn tsc --noEmit --skipLibCheck --strict # TypeScript kontrolleri çalıştırıyoruz.
